apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: prioritized-workflow-
spec:
  priority: 10
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["Priority matters!"]
