apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: create-deployment-
spec:
  entrypoint: create-k8s-deployment
  templates:
  - name: create-k8s-deployment
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                - containerPort: 80
