apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: basic-dag-demo-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: "Running task A"}]
      - name: B
        template: echo
        dependencies: [A]
        arguments:
          parameters: [{name: message, value: "Running task B"}]
      - name: C
        template: echo
        dependencies: [A]
        arguments:
          parameters: [{name: message, value: "Running task C"}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [echo, "{{inputs.parameters.message}}"]
