apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: complex-dag-demo-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: initialize
        template: echo
        arguments:
          parameters: [{name: message, value: "Initializing workflow"}]
      - name: branch-1
        dependencies: [initialize]
        template: echo
        when: "{{workflow.parameters.branch}} == branch1"
        arguments:
          parameters: [{name: message, value: "Executing Branch 1"}]
      - name: branch-2
        dependencies: [initialize]
        template: echo
        when: "{{workflow.parameters.branch}} == branch2"
        arguments:
          parameters: [{name: message, value: "Executing Branch 2"}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [echo, "{{inputs.parameters.message}}"]
