apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-argo
  namespace: argo-demo
spec:
  serviceAccountName: argo-workflow-sa
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["Hello, Argo Workflows!"]
