apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-admin-binding
  namespace: argo-demo
subjects:
- kind: ServiceAccount
  name: argo-workflow-sa
  namespace: argo-demo
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
