apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-workflow-
spec:
  entrypoint: use-hello-world-template
  templates:
  - name: use-hello-world-template
    steps:
    - - name: invoke-hello-world-template
        templateRef:
          name: hello-world-template
          template: hello-world
