apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-access-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default
roleRef:
  kind: Role
  name: argo-workflows-access
  apiGroup: rbac.authorization.k8s.io
