apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-user-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argo-workflows-user
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argo
  apiGroup: rbac.authorization.k8s.io
